language: haskell

env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.3
 - GHCVER=7.10.1
 - GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER

matrix:
  allow_failures:
    - env: GHCVER=head export PATH=/opt/ghc/$GHCVER/bin:$PATH
